# setup virtual environment and install dependencies
setup:
  python3 -m venv .venv
  ./.venv/bin/pip install -r requirements.txt

format:
    ruff format .
    ruff check --fix .

check:
    ruff check .
    pyright

test:
    python -m pytest
