[tool.ruff]
line-length = 80
select = ["ALL"]
ignore = [
  "ANN101", # missing-type-self
  "D213",   # multi-line-summary-second-line
  "D401",   # imperative mood
  "FA102",  # future-required-type-annotation
  "INP001", # add __init__.py
  "S603",   # subprocess-without-shell-equals-true #4045
  "RET504",  # unnecessary assign to clipboard
  # formatting
  "COM812", # trailing comma missing
  "D203",   # one-blank-line-before-class
  "D213",   # multi-line-summary-second-line
  "ISC001", # single-line-implicit-string-concatenation
  
]
